#!/usr/bin/env python3
"""
plot_gscholar.py

Purpose:
- Read enriched Google Scholar JSON: results/search_results/list_gscholar_crossref.json
- Aggregate the number of articles per publication year
- Generate a JavaScript file that:
    * Defines variable `gscholar_year_citations`
    * Plots a Plotly column chart `plotGscholarYearCitations`
    * Assigns chart to div with id `gscholarYearCitations`

Instructions for index.html:
1) Include Plotly in <head>:
   <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
2) Include this JS file:
   <script src="docs/js/gscholarYearCitations.js"></script>
3) Add a div for the chart:
   <div id="gscholarYearCitations"></div>
Chart will render automatically after the page loads.
"""

import json
from pathlib import Path

INPUT_JSON = "results/search_results/list_gscholar_crossref.json"
OUTPUT_JS = "docs/js/gscholarYearCitations.js"

def plot_gscholar():
    # Ensure output directory exists
    Path(OUTPUT_JS).parent.mkdir(parents=True, exist_ok=True)

    # Load enriched Google Scholar JSON
    with open(INPUT_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    articles = data.get("articles", [])

    # Aggregate articles per publication year
    gscholar_year_citations = {}
    for art in articles:
        # Prefer 'is-referenced-by-count', then 'citations', else 0
        citations = art.get("is-referenced-by-count")
        if citations is None:
            citations = art.get("citations", 0)
        # Publication year
        year = art.get("year")
        if not year:
            continue  # skip if no year
        year_str = str(year)
        gscholar_year_citations[year_str] = gscholar_year_citations.get(year_str, 0) + 1

    # Sort by year ascending for plotting
    sorted_years = sorted(gscholar_year_citations.keys())
    counts = [gscholar_year_citations[y] for y in sorted_years]

    # Generate JavaScript file
    js_content = f"""// Auto-generated by plot_gscholar.py
// Include Plotly in your HTML: <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
// Include this JS file: <script src="docs/js/gscholarYearCitations.js"></script>
// Add a div: <div id="gscholarYearCitations"></div>

var gscholar_year_citations = {json.dumps(gscholar_year_citations, indent=2)};

document.addEventListener("DOMContentLoaded", function() {{
    var trace = {{
        x: {sorted_years},
        y: {counts},
        type: 'bar',
        marker: {{color: '#2c5aa0'}}
    }};
    var layout = {{
        title: 'Google Scholar Articles per Year',
        xaxis: {{title: 'Year'}},
        yaxis: {{title: 'Number of Articles'}},
        margin: {{t:50, b:50}}
    }};
    window.plotGscholarYearCitations = Plotly.newPlot('gscholarYearCitations', [trace], layout, {{responsive:true}});
}});
"""

    # Write JS file
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"[INFO] JS file written to {OUTPUT_JS}")
    print("[INFO] Chart will render in div with id 'gscholarYearCitations'")

if __name__ == "__main__":
    plot_gscholar()
x
