#!/usr/bin/env python3
"""
AI Prompt / Lessons Learned - plot_gscholar.py

Title:
Plot Google Scholar Enriched Results by Year

Objective:
Read enriched Google Scholar JSON (list_gscholar_crossref.json), count articles published per year, and generate a Plotly column chart in JavaScript.

Lessons Learned / Important Notes:
- Ensure the input JSON exists and contains the key "articles".
- Some articles may lack "publication_year"; these should be skipped.
- Citation counts may appear as "is-referenced-by-count" or "citations"; use 0 if missing.
- Previous attempts failed because:
  * JS variable was empty (articles not found)
  * x-axis was not explicitly set, causing misaligned charts
  * File paths in HTML included 'docs/', which broke local referencing
- Force x-axis from 1922–2026 to ensure consistent visualization.
- Always load plotly.js in index.html **before** including this JS file.
- Output JS file path: docs/js/gscholarYearCitations.js
- When including in HTML, **do not** include 'docs/' in the src path; relative to HTML file.

Input:
- results/search_results/list_gscholar_crossref.json (enriched Google Scholar JSON)
  Example structure:
  {
    "count": 462,
    "articles": [
      {
        "title": "...",
        "publication_year": "1982",
        "citations": 4939,
        "is-referenced-by-count": 4939,
        ...
      },
      ...
    ]
  }

Output:
- docs/js/gscholarYearCitations.js
- JS variable: gscholar_year_citations
- Plotly chart variable: plotGscholarYearCitations
- Chart assigned to <div id="gscholarYearCitations">

Approach:
1. Load JSON, validate presence of articles.
2. Iterate articles, extract publication year and citation count.
3. Count number of articles per year.
4. Sort years for x-axis; counts for y-axis.
5. Generate JS file defining:
   - gscholar_year_citations variable
   - Plotly bar chart (plotGscholarYearCitations)
6. Force x-axis range to 1922–2026 for consistent visualization.
7. Ensure output folder exists before writing JS.
8. Include in index.html **after plotly.js** with:
   <script src="js/gscholarYearCitations.js"></script>
   <div id="gscholarYearCitations"></div>

"""

import json
import os
from pathlib import Path

INPUT_JSON = "results/search_results/list_gscholar_crossref.json"
OUTPUT_JS = "docs/js/gscholarYearCitations.js"

def plot_gscholar():
    # Load JSON
    if not os.path.exists(INPUT_JSON):
        print(f"[ERROR] Input JSON not found: {INPUT_JSON}")
        return

    with open(INPUT_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    articles = data.get("articles", [])
    if not articles:
        print("[WARN] No articles found in JSON.")
        return

    # Count articles per year
    gscholar_year_citations = {}
    for art in articles:
        year = art.get("publication_year")
        if not year:
            continue
        # Increment count of articles for this year
        gscholar_year_citations[year] = gscholar_year_citations.get(year, 0) + 1

    # Sort years
    years_sorted = sorted(gscholar_year_citations.keys(), key=int)
    counts_sorted = [gscholar_year_citations[y] for y in years_sorted]

    # Force x-axis range
    forced_min_year = 1922
    forced_max_year = 2026

    # Prepare JS content
    js_lines = [
        "// Auto-generated by plot_gscholar.py",
        "// Include this file in your index.html after loading plotly.js",
        "// Render chart in a div with id='gscholarYearCitations'",
        f"var gscholar_year_citations = {json.dumps(gscholar_year_citations, indent=2)};",
        "",
        "// Prepare Plotly chart",
        "var trace = {",
        "    x: " + json.dumps(years_sorted) + ",",
        "    y: " + json.dumps(counts_sorted) + ",",
        "    type: 'bar',",
        "    marker: {color: '#2c5aa0'}",
        "};",
        "var layout = {",
        "    title: 'Google Scholar Articles Published per Year',",
        f"    xaxis: {{title: 'Year', range: [{forced_min_year}, {forced_max_year}] }},",
        "    yaxis: {title: 'Number of Articles'}",
        "};",
        "var plotGscholarYearCitations = [trace];",
        "Plotly.newPlot('gscholarYearCitations', plotGscholarYearCitations, layout);"
    ]

    # Ensure output directory exists
    Path(os.path.dirname(OUTPUT_JS)).mkdir(parents=True, exist_ok=True)

    # Write JS file
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write("\n".join(js_lines))

    print(f"[INFO] JS file generated: {OUTPUT_JS}")
    print(f"[INFO] {len(articles)} articles processed, {len(gscholar_year_citations)} years found.")

if __name__ == "__main__":
    plot_gscholar()
